version: "3.4"
services:
  web:
    container_name: cmsp
    image: registry.gitlab.com/ginblades/docker-php-apache:65e3a96-dev
    working_dir: /app
    volumes:
      - .:/app
    command: ["tail", "-f", "/dev/null"]
